name: feedback_system_synthetic_data_generation
channels:
  - defaults
  - anaconda
dependencies:
  - python=3.11
  - pandas
  - numpy
  - pip
  - seaborn
  - matplotlib
  - psutil
  - xlsxwriter
  - openpyxl
